language: perl
perl:
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y pandoc
  - cpanm --quiet --installdeps --notest .
  - cpanm -n Devel::Cover::Report::Coveralls
script:
  perl Build.PL && ./Build build && cover -test -report coveralls
